language: cpp

git:
  depth: 3

matrix:
  include:
  - name: "Visual Studio 2017"
    os: windows
    env:
      - MONO_ROOT="C:\\Program Files\\Mono"
      - OPENALDIR="C:\\Program Files (x86)\\OpenAL 1.1 SDK"
    before_script:
      - choco install mono
      - choco install openal

script:
  - mkdir build && cd build
  - cmake $CMAKE_FLAGS ..
  - cmake --build .
